### ISSUE TITLE
Authentication Can Be Simplified

### ISSUE THREAD

**Issue by kins-dev** [thomas-bingel/iGrill#1]
So I'm letting you know because I've reworked the python code in my project, the authentication can be simplified and you don't need encryption keys.

See <https://blog.kins.dev/2019/04/igrill-device-support-for-igrill-smoker.html> for details, but basically if you pass a challenge of all 0's, you can pass back the iGrill response as your response.

Should simplify your code some.

**Comment by thomas-bingel** [comment]
Thank you for your issue. I really appreciate it. My first issue :-) I would like to leave the authentication as it is, since I tested it with the neighbors iGrill mini and it worked fine. Thanks again, I will close the issue.
